

Artist.create(name: "Khruangbin" , bio: "Khruangbin are an American musical trio from Houston, Texas, with Laura Lee on bass, Mark Speer on guitar, and Donald Ray DJ Johnson Jr. on drums. The band is known for blending global music influences, such as classic soul, dub and psychedelia. Their debut studio album, The Universe Smiles Upon You (2015), draws from the history of Thai music in the 1960s, specifically from Luk thung, while their second album, Con Todo El Mundo (2018), has influences from Spain and the Middle East. Speer, Lee, and DJ also host AirKhruang radio shows on NTS Radio and Facebook Live.",img: "https://podlink.media/show/1496922849/ep/aHR0cDovL3BpY3R1cmVzLW9mLWxpbHkuY29tLz9wPTEwODg4")
Artist.create(name: "Mos Def" , bio: "Yasiin Bey (born Dante Terrell Smith, December 11, 1973), better known by his stage name Mos Def, is an American rapper, singer, songwriter, and actor. Best known for his music, Bey began his hip hop career in 1994, alongside his siblings in the short-lived rap group Urban Thermo Dynamics (UTD), after which he appeared on albums by Da Bush Babees and De La Soul. He subsequently formed the duo Black Star, alongside fellow Brooklyn-based rapper Talib Kweli, and they released their eponymous debut album in 1998. He was featured on the roster of Rawkus Records and in 1999 released his solo debut, Black on Both Sides. His debut was followed by The New Danger (2004), True Magic (2006), and The Ecstatic (2009). The editors of About.com listed him as the 14th greatest rapper on their 50 Greatest MC's of Our Time (1987-2007) list. Some of Mos Def's top hits include Oh No, Definition, and Respiration.",img: "https://img.discogs.com/MgvRR3K4aBazS4l55OjA7h54WE0=/600x628/smart/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/A-5648-1504767680-9060.jpeg.jpg")
Artist.create(name: "Tash Sultana", bio: "Sultana grew up in Melbourne, and has been playing guitar from the age of three, beginning a career in music through busking. An active musician on Bandcamp since 2013, Sultana's recordings were viewed millions of times on YouTube in 2016. Sultana's EP, Notion, was released on 23 September 2016, followed by a sold-out world tour in early 2017.", img: "https://amnplify.com.au/tash-sultana-nominated-for-four-aria-awards")

Album.create(artist_id: "1", name: "The Universe Smiles upon You", img: "https://th.bing.com/th/id/OIP.GiHqopuqullf8ywAq9jwhAHaHa?pid=ImgDet&rs=1")
Album.create(artist_id: "1", name: "Con Todo El Mundo", img: "https://static.qobuz.com/images/covers/ga/lh/t3fa6pcr3lhga_600.jpg")
Album.create(artist_id: "1", name: "Mordechai", img: "https://az721511.vo.msecnd.net/images/1800/9002041.JPG")

Album.create(artist_id: "2", name: "Black on Both Sides ", img: "https://img.discogs.com/E5r5tzuKvSN3j1W6-Rm2jOUx7-M=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6790128-1426791441-5750.jpeg.jpg")
Album.create(artist_id: "2", name: "The New Danger ", img: "https://img.discogs.com/8xaS3dez8RMGWUHqcwJyqgBgl8I=/fit-in/500x500/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9572585-1482967331-7822.jpeg.jpg")
Album.create(artist_id: "2", name: "The Ecstatic", img: "https://img.discogs.com/MAh86N52vkpo-Juv_fuwSaIZPCA=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9662718-1508698408-4447.jpeg.jpg")

Album.create(artist_id: "3", name: "Flow State", img: "https://img.discogs.com/stofz2jaGdB0e1d2yzYewwmv-ag=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-12466814-1535854395-2540.jpeg.jpg")
Album.create(artist_id: "3", name: "Terra Firma", img: "https://static.qobuz.com/images/covers/ka/m7/eiqqpk3vpm7ka_600.jpg")

Song.create(album_id: 1, name: "Mr. White")
Song.create(album_id: 1, name: "Two Fish and an Elephant")
Song.create(album_id: 1, name: "Dern Kala")
Song.create(album_id: 2, name: "Cómo Me Quieres")
Song.create(album_id: 2, name: "Lady and Man")
Song.create(album_id: 2, name: "Maria También" )
Song.create(album_id: 3, name: "First Class")
Song.create(album_id: 3, name: "Time (You and I)")
Song.create(album_id: 3, name: "Connaissais de Face")

Song.create(album_id: 4, name: "Umi Says")
Song.create(album_id: 4, name: "Mathematics")
Song.create(album_id: 4, name: "May–December")
Song.create(album_id: 5, name: "The Boogie Man Song")
Song.create(album_id: 5, name: "Sunshine")
Song.create(album_id: 5, name: "The Panties")
Song.create(album_id: 6, name: "No Hay Nada Mas")
Song.create(album_id: 6, name: "Pretty Dancer")
Song.create(album_id: 6, name: "Revelations")

Song.create(album_id: 7, name: "Big Smoke")
Song.create(album_id: 7, name: "Salvation")
Song.create(album_id: 7, name: "Free Mind")
Song.create(album_id: 8, name: "Pretty Lady")
Song.create(album_id: 8, name: "Vanilla Honey")
Song.create(album_id: 8, name: "Let the Light In")

Review.create(artist_id: 1 , description: "This Band is everything you could ask for in a group")
Review.create(artist_id: 1 , description: "My new favorite band")
Review.create(artist_id: 1 , description: "Does anyone know if they have made comments about starting to tour again")
Review.create(artist_id: 2 , description: "This man is what rap should be")
Review.create(artist_id: 2 , description: "My favorite rapper hands down")
Review.create(artist_id: 2 , description: "This man is more than just a rapper")
Review.create(artist_id: 3 , description: "The love child of the expendable and pink floyd")
Review.create(artist_id: 3 , description: "They make music for the soul")
Review.create(artist_id: 3 , description: "Make this band mainstream")

Review.create(album_id: 1 , description: "This album ROCKS!!")
Review.create(album_id: 1 , description: "Not my favorite from them")
Review.create(album_id: 1 , description: "Definetly added to the favorite playlist")
Review.create(album_id: 2 , description: "New favorite album")
Review.create(album_id: 2 , description: "This album is incredible")
Review.create(album_id: 2 , description: "If they keep dropping albums like this they will be legends")
Review.create(album_id: 3 , description: "This album made them my new favorite band")
Review.create(album_id: 3 , description: "This is what I have come to expect from this band. Never dissapoint.")
Review.create(album_id: 3 , description: "My socks just came flying off this rocks so hard!!")
Review.create(album_id: 4 , description: "This is what rap should be")
Review.create(album_id: 4 , description: "Albums like this is why everyone likes 90's rappers")
Review.create(album_id: 4 , description: "More than an album, a moment in history")
Review.create(album_id: 5 , description: "Definetly more soul in this album which is saying alot from a mos def album")
Review.create(album_id: 5 , description: "He sings on this album, was not expecting that")
Review.create(album_id: 5 , description: "This album makes mos def more than just a rapper to me")
Review.create(album_id: 6 , description: "Spanish??? I can go with it")
Review.create(album_id: 6 , description: "This man always gives us something new and he kept that trend up with this album")
Review.create(album_id: 6 , description: "I dont know if this should even be considered a rap album as much as a album with rap on it")
Review.create(album_id: 7 , description: "This album is like everything I needed right now")
Review.create(album_id: 7 , description: "I love this album but my girl says it puts her to sleep")
Review.create(album_id: 7 , description: "Relaxing. Thats all I have to say. Relaxing")
Review.create(album_id: 8 , description: "This album is why I listen to there music the day it comes out")
Review.create(album_id: 8 , description: "More of amazing")
Review.create(album_id: 8 , description: "This album is why people should still have time where they just listen to music.")

Review.create(song_id: 1 , description: "YYEESSSS")
Review.create(song_id: 1 , description: "Beautiful")
Review.create(song_id: 1 , description: "This is a go to song forsure")
Review.create(song_id: 2 , description: "!!!!")
Review.create(song_id: 2 , description: "I need more music like this")
Review.create(song_id: 2 , description: "I just wrote a review!!!")
Review.create(song_id: 3 , description: "Perfect")
Review.create(song_id: 3 , description: "This song always holds it down")
Review.create(song_id: 3 , description: "Give me more just like this")
Review.create(song_id: 4 , description: "This is why I love this band")
Review.create(song_id: 4 , description: "Amazing")
Review.create(song_id: 4 , description: "Wow. They are incredible")
Review.create(song_id: 5 , description: ".... But how so good.")
Review.create(song_id: 5 , description: "I have got to listen to this more")
Review.create(song_id: 5 , description: "I listen to this all the time and still feel like I could listen to it more")
Review.create(song_id: 6 , description: "Bottle this feeling, become a millionaire")
Review.create(song_id: 6 , description: "And repeat one.")
Review.create(song_id: 6 , description: "I need more")
Review.create(song_id: 7 , description: "Clearly a great song")
Review.create(song_id: 7 , description: "More Like this would be great")
Review.create(song_id: 7 , description: "Finding songs like this is why I listen to music")
Review.create(song_id: 8 , description: "Alright. I need more")
Review.create(song_id: 8 , description: "Clearly a great song")
Review.create(song_id: 8 , description: "You can always use a song like this in your playlist")
Review.create(song_id: 9 , description: "This is getting added to the library")
Review.create(song_id: 9 , description: "More. I just need more")
Review.create(song_id: 9 , description: "What music should be")
Review.create(song_id: 10 , description: "Pure gold")
Review.create(song_id: 10 , description: "Reallly??? Id say pure platinum.")
Review.create(song_id: 10 , description: "Thats cool. No really it is. Im going diamond though.... I win")
Review.create(song_id: 11 , description: "So much music. And yet this is still one of my favorites")
Review.create(song_id: 11 , description: "Perfect")
Review.create(song_id: 11 , description: "This is everything I want in a song")
Review.create(song_id: 12 , description: "This is a review")
Review.create(song_id: 12 , description: "Keep the reviews coming")
Review.create(song_id: 12 , description: "Totally awesome song")
Review.create(song_id: 13 , description: "This song is like monstery energy in mp3")
Review.create(song_id: 13 , description: "quality")
Review.create(song_id: 13 , description: "great song")
Review.create(song_id: 14 , description: "Everything I listen to by them impresses me more and more")
Review.create(song_id: 14 , description: "Fantastic")
Review.create(song_id: 14 , description: "Ill never get enough of this")
Review.create(song_id: 15 , description: "This is going repeat one forsure")
Review.create(song_id: 15 , description: "3 michelin star of music")
Review.create(song_id: 15 , description: "New favorite")
Review.create(song_id: 16 , description: "I need more")
Review.create(song_id: 16 , description: "..... Just amazing")
Review.create(song_id: 16 , description: "If the whole album was like this youd be a legend")
Review.create(song_id: 17 , description: "Legend status for sure")
Review.create(song_id: 17 , description: "This isnt even realluy my type of music and Im a fan")
Review.create(song_id: 17 , description: "top notch")
Review.create(song_id: 18 , description: "Great")
Review.create(song_id: 18 , description: "Amazing")
Review.create(song_id: 18 , description: "Every positive adjective you can think of")
Review.create(song_id: 19 , description: "Beautiful")
Review.create(song_id: 19 , description: "I need more songs like this")
Review.create(song_id: 19 , description: "Mind Blown")
Review.create(song_id: 20 , description: "They deliver again")
Review.create(song_id: 20 , description: "OMG I just wrote a review")
Review.create(song_id: 20 , description: "Best ever")
Review.create(song_id: 21 , description: "If music could be tasty this would be it")
Review.create(song_id: 21 , description: "Incredible")
Review.create(song_id: 21 , description: "New favorite song")
Review.create(song_id: 22 , description: "This is why I love this band")
Review.create(song_id: 22 , description: "This is amazing")
Review.create(song_id: 22 , description: "Must listen")
Review.create(song_id: 23 , description: "Thumbs up for sure")
Review.create(song_id: 23 , description: "Wow this is good music")
Review.create(song_id: 23 , description: "This song made me decide to deep dive this band")
Review.create(song_id: 24 , description: "I could listen to this every day")
Review.create(song_id: 24 , description: "Great Song")
Review.create(song_id: 24 , description: "This is perfect.")

Genre.create(name: "Alternative Rock")
Genre.create(name: "Hip Hop/Rap")
Genre.create(name: "Electronic")
Genre.create(name: "R&B")
Genre.create(name: "Country")
Genre.create(name: "Indie Rock")
